### ISSUE TITLE
No docker images created

### ISSUE THREAD

**Issue by schellingerhout** [IBM/hyperledger-fabric-on-linux-one#15]
I followed the steps up to step 29 at which point
    
    docker ps -a 

shows no docker images.

Tested with both the generic and the hackathon images

**Comment by likepunk** [comment]
@schellingerhout , what does it say when you do this?

docker images

**Comment by SweetJenn23** [comment]
This has been fixed. There is an updated version of the script in the repo.

**Comment by schellingerhout** [comment]
@likepunk  I can see the hyperledger images:
```
hyperledger/fabric-ca        s390x-1.0.1         11f2750b6241        5 weeks ago         255MB
hyperledger/fabric-couchdb   s390x-1.0.1         d62a5ddae4fd        5 weeks ago         1.62GB
hyperledger/fabric-orderer   s390x-1.0.1         7f3a1e8da56c        5 weeks ago         194MB
hyperledger/fabric-peer      s390x-1.0.1         3b14138cde48        5 weeks ago         197MB
hyperledger/fabric-ccenv     s390x-1.0.1         dfc9d715c960        5 weeks ago         1.39GB
hyperledger/fabric-ca        s390x-1.0.0-rc1     4af4e653baf8        2 months ago        254MB
hyperledger/fabric-couchdb   s390x-1.0.0-rc1     98a34e01db51        2 months ago        1.62GB
hyperledger/fabric-orderer   s390x-1.0.0-rc1     6892ba4e63a5        2 months ago        194MB
hyperledger/fabric-peer      s390x-1.0.0-rc1     eb296fb20de8        2 months ago        197MB
```
@SweetJenn23 I still receive an error with the newer script. I think some architecture environment variable needs to be set.

```
Development only script for Hyperledger Fabric control
Running 'startFabric.sh'
FABRIC_VERSION is unset, assuming hlfv1
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
/data/linux1/composer-tools/packages/fabric-dev-servers/fabric-scripts/hlfv1/startFabric.sh: line 1: !/bin/bash: No such file or directory

# Grab the current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd
 dirname "${BASH_SOURCE[0]}"

#
cd "${DIR}"/composer

docker-compose -f "${DIR}"/composer/docker-compose.yml down
WARNING: The ARCH variable is not set. Defaulting to a blank string.
Removing network composer_default
docker-compose -f "${DIR}"/composer/docker-compose.yml up -d
WARNING: The ARCH variable is not set. Defaulting to a blank string.
Creating network "composer_default" with the default driver
ERROR: no such image: hyperledger/fabric-ca:-1.0.1: invalid reference format
```

**Comment by pramodramdas** [comment]
Facing same issue, tried setting ARCH to environment variable. Still getting the error.
Tried setting ARCH inside script, but every time fresh copy of scripts will be downloaded. So changes don't persisit.

**Comment by schellingerhout** [comment]
@pramodramdas the only way I could fix it was to completely clean the image removing all docker images all install scripts etc. Once I did that, it worked. In fact, it may just be easier to start from scratch

**Comment by jsmundey** [comment]
Just in case docker-compose is being used as a container, the script may lead to run into issue and not able to set ARCH variable. A small change in startFabric.sh, stopFabric.sh, tearDownFabric.sh

add following line below ARCH=`uname -m`

export COMPOSE_OPTIONS="-e ARCH=$ARCH"

and give it a try.

**Versions on my setup:**
hyperledger = hlfv11
docker = Docker version 17.12.1-ce, build 7390fc6
docker-compose (it's a container) = docker-compose version 1.21.0, build 5920eb0

**Comment by thekaleidoscope** [comment]
Just in case someone still has this problem, make a `.env` file in the project directory and enter following values into them

    COMPOSE_PROJECT_NAME=net
    IMAGE_TAG=latest
